title:              Nick Levantis 
email:              nicklevantis@gmail.com
description:        music & artwork 
author:             Nick Levantis 
baseurl:            ""
url:                "https://nicklevantis.com"

# Social Profiles
twitter_username:   nicklevantis
github_username:    
facebook_username:  
soundcloud_username: nicklevantis

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
